# Generated by Django 5.2.7 on 2026-03-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('author_name', models.CharField(default='Bobur Mirzo', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
